version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      -  MONGODB_USER=root
      -  MONGODB_PASS=password
    volumes:
      - './data/mongodb:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles  
  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:4.0
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  app:
    build: .
    command: /bin/sh -c "rm -f /yuruspo_bot/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/yuruspo_bot
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - mongodb
    environment:
      - YURUSPO_LINE_CHANNEL_FOR_USER_SECRET
      - YURUSPO_LINE_CHANNEL_FOR_USER_TOKEN
      - YURUSPO_LINE_CHANNEL_FOR_CIRCLE_SECRET
      - YURUSPO_LINE_CHANNEL_FOR_CIRCLE_TOKEN
      - YURUSPO_LINE_CHANNEL_FOR_LOGIN_KEY
      - YURUSPO_LINE_CHANNEL_FOR_LOGIN_SECRET
      - MY_OWN_LINE_USER_ID
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      
  worker:
    build: .
    environment:
      - YURUSPO_LINE_CHANNEL_FOR_USER_SECRET
      - YURUSPO_LINE_CHANNEL_FOR_USER_TOKEN
      - YURUSPO_LINE_CHANNEL_FOR_CIRCLE_SECRET
      - YURUSPO_LINE_CHANNEL_FOR_CIRCLE_TOKEN
      - YURUSPO_LINE_CHANNEL_FOR_LOGIN_KEY
      - YURUSPO_LINE_CHANNEL_FOR_LOGIN_SECRET
      - MY_OWN_LINE_USER_ID
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/yuruspo_bot
    depends_on:
      - db
      - redis
      - mongodb
    command: bundle exec sidekiq