version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:4.0
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  app:
    build: .
    command: /bin/sh -c "rm -f /yuruspo/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/yuruspo_bot
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - YURUSPO_LINE_CHANNEL_SECRET
      - YURUSPO_LINE_CHANNEL_TOKEN
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      
  worker:
    build: .
    environment:
      - YURUSPO_LINE_CHANNEL_SECRET
      - YURUSPO_LINE_CHANNEL_TOKEN
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/yuruspo_bot
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq